

<svg class="active" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="none" width="64" height="64">
  <path d="M256 96v86M256 330v86M96 256h86M330 256h86" stroke="#000" stroke-width="24" stroke-linecap="round" class="svg-elem-1"></path>
  <circle cx="256" cy="256" r="42" fill="#000" class="svg-elem-2"></circle>
  <circle cx="256" cy="96" r="26" fill="#000" class="svg-elem-3"></circle>
  <circle cx="256" cy="416" r="26" fill="#000" class="svg-elem-4"></circle>
  <circle cx="96" cy="256" r="26" fill="#000" class="svg-elem-5"></circle>
  <circle cx="416" cy="256" r="26" fill="#000" class="svg-elem-6"></circle>
  <rect x="126" y="126" width="40" height="40" rx="6" fill="#000" class="svg-elem-7"></rect>
  <rect x="346" y="126" width="40" height="40" rx="6" fill="#000" class="svg-elem-8"></rect>
  <rect x="126" y="346" width="40" height="40" rx="6" fill="#000" class="svg-elem-9"></rect>
  <rect x="346" y="346" width="40" height="40" rx="6" fill="#000" class="svg-elem-10"></rect>
</svg>

<style>

/***************************************************
 * Generated by SVG Artista on 4/25/2026, 5:18:29 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 346px;
    stroke-dasharray: 346px;
  }

  100% {
    stroke-dashoffset: 692px;
    stroke-dasharray: 346px;
  }
}

@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 346px;
    stroke-dasharray: 346px;
  }

  100% {
    stroke-dashoffset: 692px;
    stroke-dasharray: 346px;
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-stroke-1 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0s both infinite,
                       animate-svg-fill-1 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.8s both infinite;
          animation: animate-svg-stroke-1 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0s both infinite,
               animate-svg-fill-1 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.8s both infinite;
}

@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 265.89378290154264px;
    stroke-dasharray: 265.89378290154264px;
  }

  100% {
    stroke-dashoffset: 531.7875658030853px;
    stroke-dasharray: 265.89378290154264px;
  }
}

@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 265.89378290154264px;
    stroke-dasharray: 265.89378290154264px;
  }

  100% {
    stroke-dashoffset: 531.7875658030853px;
    stroke-dasharray: 265.89378290154264px;
  }
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-stroke-2 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.2s both infinite,
                       animate-svg-fill-2 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.9s both infinite;
          animation: animate-svg-stroke-2 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.2s both infinite,
               animate-svg-fill-2 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 0.9s both infinite;
}

@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-stroke-3 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.4s both infinite,
                       animate-svg-fill-3 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1s both infinite;
          animation: animate-svg-stroke-3 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.4s both infinite,
               animate-svg-fill-3 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1s both infinite;
}

@-webkit-keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-stroke-4 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.6000000000000001s both infinite,
                       animate-svg-fill-4 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.1s both infinite;
          animation: animate-svg-stroke-4 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.6000000000000001s both infinite,
               animate-svg-fill-4 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.1s both infinite;
}

@-webkit-keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-stroke-5 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.8s both infinite,
                       animate-svg-fill-5 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.2000000000000002s both infinite;
          animation: animate-svg-stroke-5 1.5s cubic-bezier(0.77, 0, 0.175, 1) 0.8s both infinite,
               animate-svg-fill-5 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.2000000000000002s both infinite;
}

@-webkit-keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 165.36281798666926px;
    stroke-dasharray: 165.36281798666926px;
  }

  100% {
    stroke-dashoffset: 330.7256359733385px;
    stroke-dasharray: 165.36281798666926px;
  }
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-stroke-6 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1s both infinite,
                       animate-svg-fill-6 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.3s both infinite;
          animation: animate-svg-stroke-6 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1s both infinite,
               animate-svg-fill-6 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.3s both infinite;
}

@-webkit-keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-stroke-7 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.2000000000000002s both infinite,
                       animate-svg-fill-7 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.4000000000000001s both infinite;
          animation: animate-svg-stroke-7 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.2000000000000002s both infinite,
               animate-svg-fill-7 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.4000000000000001s both infinite;
}

@-webkit-keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-stroke-8 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.4000000000000001s both infinite,
                       animate-svg-fill-8 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.5s both infinite;
          animation: animate-svg-stroke-8 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.4000000000000001s both infinite,
               animate-svg-fill-8 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.5s both infinite;
}

@-webkit-keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-stroke-9 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.6s both infinite,
                       animate-svg-fill-9 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.6s both infinite;
          animation: animate-svg-stroke-9 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.6s both infinite,
               animate-svg-fill-9 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.6s both infinite;
}

@-webkit-keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 150.73764038085938px;
    stroke-dasharray: 150.73764038085938px;
  }

  100% {
    stroke-dashoffset: 301.47528076171875px;
    stroke-dasharray: 150.73764038085938px;
  }
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(0, 0, 0);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-stroke-10 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.8s both infinite,
                       animate-svg-fill-10 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.7000000000000002s both infinite;
          animation: animate-svg-stroke-10 1.5s cubic-bezier(0.77, 0, 0.175, 1) 1.8s both infinite,
               animate-svg-fill-10 0.7s cubic-bezier(0.165, 0.84, 0.44, 1) 1.7000000000000002s both infinite;
}


</style>